### ISSUE TITLE
bug in Ekman depth limiter

### ISSUE THREAD

**Issue by vanroekel** [CVMix/CVMix-src#79]
Reported by Patrick Scholz at AWI.

The Ekman depth limiting in the boundary layer should only be applied under stable forcing, but the code is missing this check, see here
```
 if (CVmix_kpp_params_in%lEkman) then
      if (Coriolis.eq.cvmix_zero) then
        ! Rather than divide by zero, set Ekman depth to ocean bottom
        Ekman = abs(zt_cntr(nlev))
      else
        Ekman = 0.7_cvmix_r8*surf_fric/abs(Coriolis)
      end if
      OBL_limit = min(OBL_limit, Ekman)
 end if
```
The fix would be to add something like in the Monin Obukhov limiter code, i.e.
```
 if (CVmix_kpp_params_in%lEkman) then
     lstable = (surf_buoy.gt.cvmix_zero)

      if (Coriolis.eq.cvmix_zero or .not. lstable) then
        ! Rather than divide by zero or when unstable forcing, set Ekman depth to ocean bottom
        Ekman = abs(zt_cntr(nlev))
      else
        Ekman = 0.7_cvmix_r8*surf_fric/abs(Coriolis)
      end if
      OBL_limit = min(OBL_limit, Ekman)
 end if
```

**Comment by mnlevy1981** [comment]
I'm out of town, but will be back July 2nd -- I'll compare CVMix and the old POP code when I get back. I think there are three options:

1. This is a bug I introduced when putting CVMix together
1. This is a bug that existed in the original POP code and then I faithfully reproduced it in CVMix
1. There actually is a stability check, but it's buried in another part of the code

It sounds like the last is not the case, because Patrick is running into problems that can avoided with your code modification above? I'll try to have a PR put together next week.

**Comment by vanroekel** [comment]
Given my emails with Patrick,  I'm pretty certain (3) is not the case.  When Patrick set lEkman = .true. there was no boundary layer deepening in the destabilizing cases.  He has not tested my code mod proposed above, I can ask him to test or could ask him to test a PR you pull together too.  I'm also fine to make a PR based on the code mod I propose above if you'd like.

**Comment by mnlevy1981** [comment]
@vanroekel If you wanted to put together a PR and ask Patrick to test it, that would be great. I'll investigate as promised, mostly because I'm curious if this bug dates back to POP or if I fat-fingered something.

**Comment by vanroekel** [comment]
@mnlevy1981 I've pulled together the PR (#80 ) I've pinged Patrick for testing.  Once he confirms this works, I'll comment on the PR.

**Comment by mnlevy1981** [comment]
Great, thanks for taking the lead on this!
